# Generated by Django 5.2.8 on 2025-12-24 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_auth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Telegram Auth Date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Telegram Raw Data'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram First Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Last Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Telegram Photo URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Уникальный идентификатор пользователя в Telegram', null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Django User'),
        ),
    ]
