# Generated by Django 5.2.8 on 2025-12-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_userprofile_options_and_more'),
    ] 

    operations = [
        migrations.AddField(
            model_name='question',
            name='placeholder',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('info', 'Информационный блок'), ('text', 'Текстовый ответ'), ('text_area', 'Большой текстовый ответ'), ('number', 'Числовой ответ'), ('scale', 'Числовой ответ от 1 до 10'), ('date', 'Дата'), ('single_choice', 'Один вариант'), ('multiple_choice', 'Несколько вариантов'), ('select', 'Выпадающий список (один вариант)')], default='text', max_length=20),
        ),
    ]
