# Generated by Django 5.2.8 on 2025-12-23 10:50

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Уникальный идентификатор пользователя в Telegram', null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, help_text='Имя пользователя в Telegram (без @)', max_length=255, null=True, verbose_name='Telegram Username')),
                ('telegram_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram First Name')),
                ('telegram_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Last Name')),
                ('telegram_photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Telegram Photo URL')),
                ('telegram_auth_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Telegram Auth Date')),
                ('telegram_data', models.JSONField(blank=True, default=dict, help_text='Оригинальные данные полученные от Telegram', verbose_name='Telegram Raw Data')),
                ('username', models.CharField(blank=True, help_text='Не требуется для Telegram аутентификации', max_length=150, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('is_telegram_user', models.BooleanField(default=True, verbose_name='Is Telegram User')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='telegram_user_set', related_query_name='telegram_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='telegram_user_set', related_query_name='telegram_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'db_table': 'telegram_auth_user',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
