# Generated by Django 5.2.8 on 2025-12-24 00:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Уникальный идентификатор пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
                ('telegram_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram First Name')),
                ('telegram_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Last Name')),
                ('telegram_photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Telegram Photo URL')),
                ('telegram_auth_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Telegram Auth Date')),
                ('telegram_data', models.JSONField(blank=True, default=dict, verbose_name='Telegram Raw Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Django User')),
            ],
            options={
                'verbose_name': 'Telegram User Profile',
                'verbose_name_plural': 'Telegram User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
 