# Generated by Django 5.2.8 on 2025-12-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0002_telegramuserprofile_delete_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUserProfile',
        ),
    ]
